-- Formato para MySQL

CREATE DATABASE CLINICA;
USE CLINICA;

CREATE TABLE NIVELSISTEMA(
    ID_NIVELSISTEMA     SMALLINT NOT NULL AUTO_INCREMENT,    
    DESCRICAO_NIVELSISTEMA VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID_NIVELSISTEMA)    
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Senha VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE CARGO (
    ID_CARGO            TINYINT NOT NULL AUTO_INCREMENT,
    NOME_CARGO          VARCHAR (45) NOT NULL,
    DESCRICAO_CARGO     VARCHAR (120),
    PRIMARY KEY (ID_CARGO)
);

CREATE TABLE ESPECIALIDADE( 
ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
NOME_ESPECIALIDADE VARCHAR (45) NOT NULL,
PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE MEDICO (
    ID_MEDICO           INT NOT NULL AUTO_INCREMENT,
    ID_CARGO            TINYINT NOT NULL,
    ID_ESPECIALIDADE    INT NOT NULL,
    NOME_ESPECIALIDADE  VARCHAR(45) NOT NULL,
    NOME_MEDICO         VARCHAR(45) NOT NULL, 
    CRM_MEDICO          VARCHAR(10) NOT NULL UNIQUE,
    CPF_MEDICO          VARCHAR(13) NOT NULL UNIQUE,
    RG_MEDICO           VARCHAR(13) NOT NULL UNIQUE,
    CIDADE_MEDICO       VARCHAR(45) NOT NULL,
    TELEFONE_MEDICO     VARCHAR(13) NOT NULL,
    CELULAR_MEDICO      VARCHAR(13) NOT NULL,
    EMAIL_MEDICO        VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID_MEDICO),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

CREATE TABLE STATUSPACIENTE (
    ID_STATUSPACIENTE   SMALLINT NOT NULL AUTO_INCREMENT,
    NOME_STATUSPACIENTE VARCHAR (30) NOT NULL,
    PRIMARY KEY (ID_STATUSPACIENTE)
);

CREATE TABLE PACIENTE (
    ID_PACIENTE          INT NOT NULL AUTO_INCREMENT,
    ID_STATUSPACIENTE    SMALLINT NOT NULL,  
    ID_MEDICO            INT NOT NULL,
    NOME_PACIENTE        VARCHAR (45) NOT NULL,     
    CPF_PACIENTE         VARCHAR (13) NOT NULL UNIQUE,
    RG_PACIENTE          VARCHAR (13) NOT NULL UNIQUE,
    CIDADE_PACIENTE      VARCHAR (45) NOT NULL,
    TELEFONE_PACIENTE    VARCHAR (45) NOT NULL,
    CELULAR_PACIENTE     VARCHAR (13) NOT NULL,
    PRIMARY KEY (ID_PACIENTE),
    FOREIGN KEY (ID_STATUSPACIENTE) REFERENCES STATUSPACIENTE(ID_STATUSPACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO)
);

CREATE TABLE AGENDA (
    ID_AGENDA           INT NOT NULL AUTO_INCREMENT,
    ID_PACIENTE         INT NOT NULL,
    DATA_AGENDA         DATE NOT NULL,
    HORA_AGENDA         TIME NOT NULL,
    PRIMARY KEY (ID_AGENDA),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE CONSULTAS (
    ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
    ID_MEDICO INT NOT NULL,
    ID_Paciente INT NOT NULL,
    DataConsulta DATE NOT NULL,
    HoraConsulta TIME NOT NULL,
    PRIMARY KEY (ID_CONSULTA),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_Paciente) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE HISTORICO_CONSULTAS (
    ID_HistoricoConsulta INT NOT NULL AUTO_INCREMENT,
    ID_MEDICO INT NOT NULL,
    ID_Paciente INT NOT NULL,
    DataConsulta DATE NOT NULL,
    HoraConsulta TIME NOT NULL,
    Diagnostico TEXT NOT NULL,
    Prescricoes TEXT,
    PRIMARY KEY (ID_HistoricoConsulta),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_Paciente) REFERENCES Paciente(ID_Paciente)
);

-- Formato para PostegreSQL

-- Criação do banco de dados
CREATE DATABASE CLINICA;
\c CLINICA;  -- Muda para o banco de dados CLINICA

-- Tabela NIVELSISTEMA
CREATE TABLE NIVELSISTEMA (
    ID_NIVELSISTEMA SERIAL PRIMARY KEY,
    DESCRICAO_NIVELSISTEMA VARCHAR(20) NOT NULL
);

-- Tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO SERIAL PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    EMAIL_FUNCIONARIO VARCHAR(50) UNIQUE,
    SENHA_FUNCIONARIO VARCHAR(50) NOT NULL
);

-- Tabela CARGO
CREATE TABLE CARGO (
    ID_CARGO SERIAL PRIMARY KEY,
    NOME_CARGO VARCHAR(45) NOT NULL,
    DESCRICAO_CARGO VARCHAR(120)
);

-- Tabela ESPECIALIDADE
CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE SERIAL PRIMARY KEY,
    NOME_ESPECIALIDADE VARCHAR(45) NOT NULL
);

-- Tabela MEDICO
CREATE TABLE MEDICO (
    ID_MEDICO SERIAL PRIMARY KEY,
    ID_CARGO INT NOT NULL,
    ID_ESPECIALIDADE INT NOT NULL,
    NOME_ESPECIALIDADE VARCHAR(45) NOT NULL,
    NOME_MEDICO VARCHAR(45) NOT NULL,
    CRM_MEDICO VARCHAR(10) NOT NULL UNIQUE,
    CPF_MEDICO VARCHAR(13) NOT NULL UNIQUE,
    RG_MEDICO VARCHAR(13) NOT NULL UNIQUE,
    CIDADE_MEDICO VARCHAR(45) NOT NULL,
    TELEFONE_MEDICO VARCHAR(13) NOT NULL,
    CELULAR_MEDICO VARCHAR(13) NOT NULL,
    EMAIL_MEDICO VARCHAR(45) NOT NULL,
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

-- Tabela STATUSPACIENTE
CREATE TABLE STATUSPACIENTE (
    ID_STATUSPACIENTE SERIAL PRIMARY KEY,
    NOME_STATUSPACIENTE VARCHAR(30) NOT NULL
);

-- Tabela PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE SERIAL PRIMARY KEY,
    ID_STATUSPACIENTE INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    NOME_PACIENTE VARCHAR(45) NOT NULL,
    CPF_PACIENTE VARCHAR(13) NOT NULL UNIQUE,
    RG_PACIENTE VARCHAR(13) NOT NULL UNIQUE,
    CIDADE_PACIENTE VARCHAR(45) NOT NULL,
    TELEFONE_PACIENTE VARCHAR(45) NOT NULL,
    CELULAR_PACIENTE VARCHAR(13) NOT NULL,
    FOREIGN KEY (ID_STATUSPACIENTE) REFERENCES STATUSPACIENTE(ID_STATUSPACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO)
);

-- Tabela AGENDA
CREATE TABLE AGENDA (
    ID_AGENDA SERIAL PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    DATA_AGENDA DATE NOT NULL,
    HORA_AGENDA TIME NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

-- Tabela CONSULTAS
CREATE TABLE CONSULTAS (
    ID_CONSULTA SERIAL PRIMARY KEY,
    ID_MEDICO INT NOT NULL,
    ID_Paciente INT NOT NULL,
    DataConsulta DATE NOT NULL,
    HoraConsulta TIME NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_Paciente) REFERENCES PACIENTE(ID_PACIENTE)
);

-- Tabela HISTORICO_CONSULTAS
CREATE TABLE HISTORICO_CONSULTAS (
    ID_HistoricoConsulta SERIAL PRIMARY KEY,
    ID_MEDICO INT NOT NULL,
    ID_Paciente INT NOT NULL,
    DataConsulta DATE NOT NULL,
    HoraConsulta TIME NOT NULL,
    Diagnostico TEXT NOT NULL,
    Prescricoes TEXT,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_Paciente) REFERENCES PACIENTE(ID_PACIENTE)
);
